apply plugin: 'com.android.application'

android {
    namespace 'com.zheliu.pokehome'
    compileSdk 34

    defaultConfig {
        applicationId 'com.zheliu.pokehome'
        minSdk 23
        targetSdk 28
        versionCode 4
        versionName '4.0'
    }

    lint {
        abortOnError true
        checkReleaseBuilds true
        disable 'ExpiredTargetSdkVersion'
    }
}
